### ISSUE TITLE
Items in QTreeWidget don't show if initial Ref gets dropped.

### ISSUE THREAD

**Issue by lievenvanderheide** [rust-qt/examples#10]
With the following code:

```
use qt_core::*;
use qt_widgets::*;

fn main() {
	QApplication::init(|_| unsafe {
        	let main_window = QMainWindow::new_0a();

		let tree_widget = QTreeWidget::new_0a();
		tree_widget.set_column_count(1);

		//{
			let item = QTreeWidgetItem::from_q_string_list_int(&QStringList::from_q_string(&qs("item")), 0);
			tree_widget.add_top_level_item(&item);
		//}

		main_window.set_central_widget(&tree_widget);
		main_window.show();

		QApplication::exec()
	})
}

````

This code works as expected, but if I uncomment the two commented lines, then the item doesn't show up anymore in the QTreeWidget.

I'm sure this has something to do with the fact that the 'item' gets dropped, but is this the correct behavior? I'd expect tree_widget to take ownership of the item, so the fact that the 'item' reference goes out of scope shouldn't mean the actual QTreeWidgetItem gets deleted.

**Comment by Riateche** [comment]
Dropping or not dropping objects depending on their ownership is done by `QBox` and is only supported for `QObject`s. `QTreeWidgetItem` is not a `QObject`, so it's managed by `CppBox` instead of `QBox`. `CppBox` will always drop the contained object by default. Use `into_ptr` when passing the object to a method that takes ownership to prevent it from being deleted:
```
tree_widget.add_top_level_item(item.into_ptr());
```
It's hard to track  `QTreeWidgetItem`'s ownership automatically. To check if it's owned, you would need to access it, and there is no way to check if it has already been deleted, so accessing it automatically in `Drop` would sometimes crash.

**Comment by lievenvanderheide** [comment]
Thanks, that works.
